name: CI/CD

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.29.0
      - name: Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.12.1
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check formatting
        run: pnpm check:formatting
      - name: Check types
        run: pnpm check:types
      - name: Run tests
        run: pnpm test
      - name: Build
        run: pnpm build
      - name: Publish to NPM
        if: ${{ github.event_name == 'push' }}
        id: changesets
        uses: changesets/action@v1.4.1
        with:
          publish: pnpm publish
          commit: 'chore: publish packages'
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Debug changesets output
        run: |
          echo ${{ steps.changesets.outputs.published }}
          echo ${{ steps.changesets.outputs.publishedPackages }}
