name: CI/CD

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  main:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.29.0
      - name: Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.12.1
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Changeset status
        run: pnpm changeset status --output changeset-status.json
      - name: Find out if there is something to publish
        id: should_publish
        run: |
          const fs = require('fs')

          const changesetStatus = JSON.parse(fs.readFileSync('./changeset-status.json', { encoding: 'utf8' }))
          core.info(JSON.stringify(changesetStatus))

          if (changesetStatus.releases.length === 0) {
            core.setOutput('result', false)
          } else {
            core.setOutput('result', true)
          }
      - name: Generate changelog
        if: ${{ steps.should_publish.outputs.result == 'true' }}
        run: pnpm changeset version
      - name: Configure git
        if: ${{ steps.should_publish.outputs.result == 'true' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Build
        if: ${{ steps.should_publish.outputs.result == 'true' }}
        run: pnpm build
      - name: Setup npmrc
        if: ${{ steps.should_publish.outputs.result == 'true' }}
        run: |
          pnpm config set access public --location project
          pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }} --location project
      - name: Add files and commit changes
        if: ${{ steps.should_publish.outputs.result == 'true' }}
        run: |
          git add .
          git commit -m "chore: generate changelog\n\n[skip ci]"
      - name: Push changes
        if: ${{ steps.should_publish.outputs.result == 'true' }}
        run: git push origin main
      - name: Publish to NPM
        if: ${{ steps.should_publish.outputs.result == 'true' }}
        run: pnpm publish -r --report-summary
      - name: Debug changesets output
        if: ${{ steps.should_publish.outputs.result == 'true' }}
        run: cat pnpm-publish-summary.json
      - name: Create slack message
        if: ${{ steps.should_publish.outputs.result == 'true' }}
        id: create_slack_message
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')

            const publishSummary = JSON.parse(
              fs.readFileSync('./pnpm-publish-summary.json', { encoding: 'utf8' }),
            )

            if (publishSummary.publishedPackages.length === 0) {
              core.info('There are no packages to publish.')
              process.exit(0)
            }

            let message = '*Successfully published*\n```'
            publishSummary.publishedPackages.forEach((publishedPackage) => {
              message += `  - ${publishedPackage.name}@${publishedPackage.version}\n`
            })
            message += '```'

            core.info(message)

            core.setOutput('message', message)
      - name: Send slack message
        if: ${{ steps.should_publish.outputs.result == 'true' }}
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: C023PKSN2Q7
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.create_slack_message.outputs.message }}"
                  }
                }
              ]
            }
