name: CI/CD

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  main:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.29.0
      - name: Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.12.1
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check formatting
        run: pnpm check:formatting
      - name: Check types
        run: pnpm check:types
      - name: Run tests
        run: pnpm test
      - name: Build
        run: pnpm build
      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - name: Push changes
        run: git push origin main
      - name: Create version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          pnpm changeset version
      - name: Publish to NPM
        run: pnpm publish --report-summary
      - name: Debug changesets output
        run: cat pnpm-publish-summary.json
